/**
 * KB compiler (plan.md CH-06 steps 1-2, §6.2 block [3]). Reads the curated
 * sources under kb/source/ plus the villa identity map (src/lib/villas.ts), and
 * emits the guest-facing kb/villas.md · kb/policies.md · kb/faq.md. kb/quirks.md
 * is HAND-MAINTAINED and never written here. Enforces the block-[3] ≤6k-token
 * budget — the build THROWS (fails) if the compiled knowledge is over budget.
 *
 * Pure `buildKb()` is unit-tested (test/kb-build.test.ts); `main()` does the I/O.
 * CLI: `pnpm kb:build` (or `pnpm tsx scripts/kb-build.ts`).
 */
import { VILLAS, type Villa } from '../src/lib/villas.js';
import {
  KB_TOKEN_BUDGET,
  concatKnowledge,
  estimateKbTokens,
  kbVersion,
} from '../src/brain/knowledge.js';
import { extractRupeeAmounts } from '../src/brain/rupees.js';

interface RoomType {
  roomTypeId: string;
  maxAdults: number;
}
interface RoomTypesSource {
  roomTypes: RoomType[];
}
interface VillaContent {
  locality: string;
  bedrooms: number;
  pool: string | null;
  description: string;
}
interface VillasSource {
  villas: Record<string, VillaContent>;
}

export interface KbSources {
  villas: VillasSource;
  roomTypes: RoomTypesSource;
  /** kb/source/website-content/policies.md — guest-facing policy fragment. */
  policies: string;
  /** kb/source/website-content/faq.md — condensed FAQ fragment. */
  faq: string;
  /** kb/quirks.md — hand-maintained; passed through untouched. */
  quirks: string;
}

export interface KbBuild {
  files: { 'villas.md': string; 'policies.md': string; 'faq.md': string };
  /** The concatenated block [3] body the runtime will send (comments stripped). */
  knowledge: string;
  tokens: number;
  version: string;
}

const GENERATED = (source: string): string =>
  `<!-- GENERATED by scripts/kb-build.ts from ${source} — do not edit; edit the source and run \`pnpm kb:build\`. -->`;

function typeWord(villa: Villa): string {
  return villa.typeName === 'Nistula Apartment' ? 'apartment' : 'villa';
}

/** Joins each villa's identity (VILLAS) with its website copy (villas.json) and
 * type occupancy (roomtypes.json → "sleeps up to maxAdults"). */
function renderVillas(src: VillasSource, roomTypes: RoomTypesSource): string {
  const maxByType = new Map(roomTypes.roomTypes.map((r) => [r.roomTypeId, r.maxAdults]));

  const blocks = VILLAS.map((villa) => {
    const content = src.villas[villa.villaId];
    if (content === undefined) throw new Error(`villas.json missing content for ${villa.label} (${villa.villaId})`);
    const maxAdults = maxByType.get(villa.roomTypeId);
    if (maxAdults === undefined) throw new Error(`roomtypes.json missing room type ${villa.roomTypeId} for ${villa.label}`);

    const facts = [`${content.bedrooms}-bedroom ${typeWord(villa)} in ${content.locality}`, `sleeps up to ${maxAdults}`];
    if (content.pool !== null) facts.push(content.pool);
    return `### ${villa.label}\n${facts.join(' · ')}.\n${content.description}`;
  });

  return [
    GENERATED('kb/source/website-content/villas.json + kb/source/roomtypes.json'),
    '# The villas',
    'Nistula has eight private homes in Goa: three apartments and four villas in Assagao, and a four-bedroom villa in Siolim. Homes are booked at room-type level — the exact unit is assigned on arrival, so never promise a specific unit unless it has already been allocated. All rates are all-inclusive; quote them only from get_quote.',
    // WHY "listed on every villa page" and NOT "shared on every home": the site
    // renders ONE property-wide amenity list on every villa; it is a published
    // claim, not a verified per-villa fact. A blanket "swimming pool" here would
    // also assert a pool for Siolim, whose pool is UNCONFIRMED (OQ-09) — the very
    // claim villas.json's pool:null exists to withhold. Pools are stated ONLY by
    // each villa's own `pool` field below.
    '**Listed on every villa page (property-wide):** free Wi-Fi, air conditioning, HD TV, a full kitchen with refrigerator and coffee machine, welcome drinks, room service, laundry and dry cleaning, daily housekeeping, an in-house spa, garden views, a private entrance, contactless check-in, and free parking. We can also help arrange airport transfers, a chef and experiences through trusted partners.',
    // WHY no drive times: the website deliberately omits distances (generic-honest
    // copy), so any number here would be invented. Keep the source's own hedges.
    '**Around Assagao:** quiet green lanes in north Goa; cafés and restaurants a short drive away; the northern beaches within easy reach by car; the airport a drive away — we are glad to arrange a transfer. **Around Siolim:** quieter still — riverside north Goa, green and unhurried, the beaches a drive away.',
    ...blocks,
  ].join('\n\n');
}

/** Policies and FAQ are guest-facing already — wrap with a generated header so
 * humans edit the source, not the output. The header is an HTML comment and is
 * stripped before the block reaches the model (knowledge.ts). */
function renderPassthrough(source: string, body: string): string {
  return `${GENERATED(source)}\n\n${body.trim()}\n`;
}

/** Compiles all three files + the concatenated block [3], and enforces the
 * ≤6k-token budget (throws — the build fails — when over). */
export function buildKb(sources: KbSources): KbBuild {
  const files = {
    'villas.md': `${renderVillas(sources.villas, sources.roomTypes)}\n`,
    'policies.md': renderPassthrough('kb/source/website-content/policies.md', sources.policies),
    'faq.md': renderPassthrough('kb/source/website-content/faq.md', sources.faq),
  };
  const knowledge = concatKnowledge({
    villas: files['villas.md'],
    policies: files['policies.md'],
    faq: files['faq.md'],
    quirks: sources.quirks,
  });
  const tokens = estimateKbTokens(knowledge);
  if (tokens > KB_TOKEN_BUDGET) {
    throw new Error(
      `compiled KNOWLEDGE block is ~${tokens} tokens, over the ${KB_TOKEN_BUDGET}-token budget — ` +
        `trim kb/source/* or kb/quirks.md (plan.md §6.2).`,
    );
  }

  // Guardrail-1 only exempts fees published in kb/policies.md (§6.5). A ₹ figure
  // anywhere ELSE in block [3] is KB "truth" the guardrail is guaranteed to
  // reject — the model would state it, get blocked, and the guest would get the
  // rate-unavailable deferral plus a spurious ops escalation. quirks.md is the one
  // file non-engineers edit, so fail the BUILD rather than ship that trap.
  for (const [name, body] of [
    ['kb/villas.md', files['villas.md']],
    ['kb/faq.md', files['faq.md']],
    ['kb/quirks.md', sources.quirks],
  ] as const) {
    const stray = extractRupeeAmounts(body);
    if (stray.length > 0) {
      throw new Error(
        `${name} contains ₹ figure(s) [${stray.join(', ')}] — fees must live in kb/source/website-content/policies.md ` +
          `so guardrail 1 can exempt them (plan.md §6.5). Stay prices never belong in the KB at all: they come from get_quote.`,
      );
    }
  }

  return { files, knowledge, tokens, version: kbVersion(knowledge) };
}

async function main(): Promise<void> {
  const { readFile, writeFile } = await import('node:fs/promises');
  const readText = async (rel: string): Promise<string> => readFile(new URL(rel, import.meta.url), 'utf8');
  const readJson = async <T>(rel: string): Promise<T> => JSON.parse(await readText(rel)) as T;

  const sources: KbSources = {
    villas: await readJson<VillasSource>('../kb/source/website-content/villas.json'),
    roomTypes: await readJson<RoomTypesSource>('../kb/source/roomtypes.json'),
    policies: await readText('../kb/source/website-content/policies.md'),
    faq: await readText('../kb/source/website-content/faq.md'),
    quirks: await readText('../kb/quirks.md'),
  };

  const built = buildKb(sources);
  for (const [name, body] of Object.entries(built.files)) {
    await writeFile(new URL(`../kb/${name}`, import.meta.url), body, 'utf8');
  }
  console.log(
    `kb:build ok — wrote villas.md, policies.md, faq.md · block[3] ~${built.tokens} tokens ` +
      `(budget ${KB_TOKEN_BUDGET}) · version ${built.version}`,
  );
}

// Run only when executed directly — tests import buildKb without side effects.
if (process.argv[1]?.endsWith('kb-build.ts') === true) {
  main().catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  });
}
