/**
 * Prints the Meta template-approval pack (CH-12, plan §8 "Manual step (Paul)":
 * "runbook section written here: exact template bodies to submit, category
 * choices, variable examples").
 *
 * WHY this is a SCRIPT and not a list typed into the runbook: the bodies are
 * generated from the same `render` functions the sender actually uses, so a
 * body that gets submitted to Meta and a body that gets sent to a guest cannot
 * silently diverge. A hand-copied list would drift the first time anyone edited
 * a template — and the drift would only surface in production, on a real guest.
 *
 *   pnpm templates:pack          # paste into Meta's template manager
 */
import { LIFECYCLE_TEMPLATES, metaBody, STAFF_TEMPLATES, type TemplateDef } from '../src/lifecycle/templates.js';

function section(title: string, group: Record<string, TemplateDef>): void {
  console.log(`\n## ${title}\n`);
  for (const d of Object.values(group)) {
    console.log(`### \`${d.name}\``);
    console.log(`- **Category:** ${d.category}`);
    console.log(`- **Language:** ${d.language}`);
    console.log('- **Body:**');
    console.log('');
    console.log('```');
    console.log(metaBody(d));
    console.log('```');
    console.log('');
    if (d.order.length > 0) {
      console.log(`- **Variables:** ${d.order.map((k, i) => `\`{{${i + 1}}}\` = ${k}`).join(' · ')}`);
      const example = Object.fromEntries(d.order.map((k) => [k, EXAMPLES[k] ?? k]));
      console.log(`- **Sample (for Meta's review):** ${d.render(example)}`);
    }
    console.log('');
  }
}

/** Meta rejects a template whose sample values look like placeholders.
 *
 * 🚨 These strings are submitted to Meta for approval and then live for the life
 * of the template, so they must name a product Nistula actually lets. The three-
 * bedroom Assagao villas ("Nistula Villa") were retired 2026-07-24 (CH-20) —
 * advertising a departed type in the approval pack would bake it into the WABA. */
const EXAMPLES: Record<string, string> = {
  firstName: 'Rahul',
  villaType: 'Nistula Apartment',
  locality: 'Assagao',
  dates: '20–22 December 2026',
  reference: '953',
  checkInDay: 'Sunday 20 December',
  shortId: 'K7Q2ZP',
  villa: 'Apartment 09',
  guestName: 'Rahul',
  summary: 'two extra towels',
  reason: 'outside knowledge base',
  detail: 'Guest is planning a proposal and asks about pool decoration.',
  day: 'Monday 20 July',
  replyType: 'instay',
  body: 'Of course — two fresh towels are on their way.',
};

console.log('# Meta template approval pack (generated — do not hand-edit)');
console.log('');
console.log('Generated by `pnpm templates:pack` from src/lifecycle/templates.ts.');
console.log('Submit at real-number cutover (plan §10). Utility = service; marketing needs opt-in.');
section('Guest templates', LIFECYCLE_TEMPLATES);
section('Staff templates (§5.3 — the window rule binds staff numbers too)', STAFF_TEMPLATES);
